export const LOGIN='LOGIN';
export const LOGOUT='LOGOUT'


export const INC_COUNTER = 'INC_COUNTER';
export const DEC_COUNTER = 'DEC_COUNTER';

export const HOME_VIDEOS_SUCCESS = 'HOME_VIDEOS_SUCCESS'
export const HOME_VIDEOS_FAIL = 'HOME_VIDEOS_FAIL'
export const HOME_VIDEOS_REQUEST = 'HOME_VIDEOS_REQUEST'

export const WATCH_VIDEO_SUCCESS = 'WATCH_VIDEO_SUCCESS'
export const WATCH_VIDEO_LOADING = 'WATCH_VIDEO_LOADING'
export const WATCH_VIDEO_FAIL = 'WATCH_VIDEO_FAIL'

export const WATCH_REL_VIDEO_SUCCESS = 'WATCH_REL_VIDEO_SUCCESS'
export const WATCH_REL_VIDEO_LOADING = 'WATCH_REL_VIDEO_LOADING'
export const WATCH_REL_VIDEO_FAIL = 'WATCH_REL_VIDEO_FAIL'

export const WATCH_CHANNEL_SUCCESS = 'WATCH_CHANNEL_SUCCESS'
export const WATCH_CHANNEL_LOADING = 'WATCH_CHANNEL_LOADING'
export const WATCH_CHANNEL_FAIL = 'WATCH_CHANNEL_FAIL'

export const WATCH_COMMENTS_SUCCESS = 'WATCH_COMMENTS_SUCCESS'
export const WATCH_COMMENTS_LOADING = 'WATCH_COMMENTS_LOADING'
export const WATCH_COMMENTS_FAIL = 'WATCH_COMMENTS_FAIL'


export const WATCH_MORE_COMMENTS_SUCCESS = 'WATCH_MORE_COMMENTS_SUCCESS'
export const WATCH_MORE_COMMENTS_LOADING = 'WATCH_MORE_COMMENTS_LOADING'
export const WATCH_MORE_COMMENTS_FAIL = 'WATCH_MORE_COMMENTS_FAIL'


export const LIKED_VIDEOS_LOADING = 'LIKED_VIDEOS_LOADING'
export const LIKED_VIDEOS_SUCCESS = 'LIKED_VIDEOS_SUCCESS'
export const LIKED_VIDEOS_FAIL = 'LIKED_VIDEOS_FAIL'

export const SEARCH_LOADING = 'SEARCH_LOADING'
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS'
export const SEARCH_FAIL = 'SEARCH_FAIL'

export const SUBSCRIPTION_LOADING = 'SUBSCRIPTION_LOADING'
export const SUBSCRIPTION_SUCCESS = 'SUBSCRIPTION_SUCCESS'
export const SUBSCRIPTION_FAIL = 'SUBSCRIPTION_FAIL'

export const ADD_SUBSCRIPTION = 'ADD_SUBSCRIPTION'